### ISSUE TITLE
Add Helios 300 PH315-52-748u to supported devices

### ISSUE THREAD

**Issue by RuiGuilherme** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#1]
**Kernel**: 5.12.9-arch1-1
**OS**: Arch Linux x86_64
**Device**: Acer Predator Helios 300 PH315-52-748u

1. All mode works fine.
2. Speed control works fine
3. Brightness control works fine (but has one issue with mode).
4. Direction control works fine 
5. cR, cG and cB works fine

I just had one issue: 
If you set keyboard brightness using -b the mode will be set to 3 automatically. (Control brightness using Fn + F9/F10 solve this)

### sudo dmidecode | grep "Product Name" -B 2 -A 4
```
System Information
        Manufacturer: Acer
        Product Name: Predator PH315-52
        Version: V1.12
        Serial Number: NHQ62AL001016D78C99501
        UUID: f87dea2b-75a4-471d-ae8a-586741a05036
        Wake-up Type: Power Switch
--
Base Board Information
        Manufacturer: CFL
        Product Name: Covini_CFS
        Version: V1.12
        Serial Number: NBQ5311004016018DE9501
        Asset Tag: Type2 - Board Asset Tag
        Features:

```
###  sudo cat /sys/firmware/acpi/tables/DSDT > dsdt.aml
[dsdt.aml.zip](https://github.com/JafarAkhondali/acer-helios-300-rgb-keyboard-linux-module/files/6604485/dsdt.aml.zip) (Github don't accept .aml file)

**Comment by JafarAkhondali** [comment]
Thank for the repor @RuiGuilherme, glad it worked
 
I understand the problem with brightness, that's because the script is minimal and doesn't store\use the state.
Actually I was hoping to merge the changes into Linux kernel, but some required functionalities for implementations are missing so I'm not sure to wait for them, or develop this repo.

**Comment by JafarAkhondali** [comment]
@RuiGuilherme I've added Turbo mode support as well, can you kindly please test updated version? (at your own risk 😆 )

**Comment by RuiGuilherme** [comment]
Nice! Apparently works fine and the fans were for maximum speed.

Later I will check if the UnderVolt is being removed and the overclock is being applied.

**Comment by JafarAkhondali** [comment]
Probably because it hasn't received the update. I think our CPU was build after the last commit of that repository.
btw I think turbo for helios 300 works only on GPU (not sure)

**Comment by RuiGuilherme** [comment]
Hup! You are right. Just overclock GPU, but at the time I bought this notebook it came with Windows, and it had an undervolt on the i7 9750H and Turbo Mode "Disable" this undervolt.

I don't remember the exact values because I bought this notebook in 2020, but I had used this thead to reverse the undervolt without using turbo mode. 
https://www.techpowerup.com/forums/threads/undervolt-an-i7-9750h-with-throttlestop.268380/ 

But it's like I said, maybe I'm going crazy haha
