### ISSUE TITLE
please add PH315-55

### ISSUE THREAD

**Issue by w74anheda** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#105]
this package not working in model PH315-55 
please support this model

**Comment by JafarAkhondali** [comment]
How many fans do you have per CPU and GPU?

**Comment by w74anheda** [comment]
how can find count of fans?

**Comment by w74anheda** [comment]
after install this package : https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module
backlight is working but turbo fan button is not working

**Comment by zetchz** [comment]
hi w74anheda. I have a PH315-55 too. can i check if you keyboard backlight can be controlled and whether the base board is the same? The backlight script doesnt  work for me.

---
 sudo dmidecode | grep "Product Name" -B 2 -A 4

System Information
	Manufacturer: Acer
	Product Name: Predator PH315-55

Base Board Information
	Manufacturer: ADL
	Product Name: Evoque_ADH
	Version: V1.10

**Comment by w74anheda** [comment]
> sudo dmidecode | grep "Product Name" -B 2 -A 4

hi zetchz,
yes i can controll that with listed of command in package

System Information
	Manufacturer: Acer
	Product Name: Predator PH315-55
	Version: V1.07
--
Base Board Information
	Manufacturer: ADL
	Product Name: Evoque_ADH
	Version: V1.07

**Comment by w74anheda** [comment]
> How many fans do you have per CPU and GPU?


how can find count of fans?

**Comment by bharata108mklt** [comment]
I have the same model. All functions work. 
System Information
	Manufacturer: Acer
	Product Name: Predator PH315-55
	Version: V1.05
