### ISSUE TITLE
Kernel panic on 6.5 and newer kernel

### ISSUE THREAD

**Issue by jyash8** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#111]
Model: `Nitro AN515-58`

module is sometimes causing kernel panic

mainly observed when i shutdown my pc after after not pressing backlight brightness change buttons

mainly in kernel >= 6.5

**Comment by jyash8** [comment]
so how much time could it take

**Comment by JafarAkhondali** [comment]
@jyash8 Right now I barely can find time to record videos for RE :( I hope someone can work on this

**Comment by jyash8** [comment]
I think i have maybe figured out the problem due to some reason facer module can not be removed.
I have attached the photo of the log when system panics.
![1694189352613](https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module/assets/122196951/4a6a2671-788a-43ed-9335-081bf39ae3a6)
Because when i tried to remove the facer module with modprobe it said "facer not found".
