### ISSUE TITLE
Predator PH315: turbo button

### ISSUE THREAD

**Issue by w74anheda** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#117]
after install as service, push turbo button and turbo mode is activate but after push that turbo mode is not deactivate and not working, restart my laptop but not resetting turbo mode

**Comment by amirkfir** [comment]
I experience the same problem at ph315-55, turbo buttom turning fans on, but not off, and it's stuck in on mode after reboot.

**Comment by w74anheda** [comment]
What should we do to fix it?

**Comment by JafarAkhondali** [comment]
Right now turbo mode checks for the state of the turbo LED in to see if turbo mode is activated. Temporary you can disable it in windows, but perhaps the WMI call to check turbo LED state is wrong and should be fixed.

**Comment by JafarAkhondali** [comment]
Can you check the issue again with latest version?  Uninstall - reboot - reinstall

**Comment by w74anheda** [comment]
> Can you check the issue again with latest version? Uninstall - reboot - reinstall

yes its, work. thanks for that.
