### ISSUE TITLE
Worked on PH317-53

### ISSUE THREAD

**Issue by inakrin** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#2]
Thank you so much! 
System Information
        Manufacturer: Acer            
        Product Name: Predator PH317-53
        Version: V1.02
        Serial Number: NHQ5PST00192509D812600
        UUID: 49ddfdd9-4a0a-446a-a154-cee2e382cdaa
        Wake-up Type: Power Switch
--
Base Board Information
        Manufacturer: CFL
        Product Name: Alphard_CFS
        Version: V1.02
        Serial Number: NBQ5P11006924000E42600
        Asset Tag: Type2 - Board Asset Tag
        Features:

**Comment by JafarAkhondali** [comment]
@inakrin I'm glad it helped you, thanks for letting me know
Which features did work for you? turbo or LED?

**Comment by inakrin** [comment]
@JafarAkhondali both
