### ISSUE TITLE
Predator PT515-52

### ISSUE THREAD

**Issue by ayan-r** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#26]
Does not work for my laptop.
will there be updates for this model? 

System Information
        Manufacturer: Acer
        Product Name: Predator PT515-52
        Version: V1.07
        Serial Number: ************************************
        UUID: ******************************************
        Wake-up Type: Power Switch**

Base Board Information
        Manufacturer: CML
        Product Name: Spyder_CMS
        Version: V1.07
        Serial Number: NBQ************************
        Asset Tag:                       
        Features:

file /sys/bus/wmi/devices/7A4DDFE7-5B5D-40B4-8595-4408E0CC7F56/
/sys/bus/wmi/devices/7A4DDFE7-5B5D-40B4-8595-4408E0CC7F56/: cannot open `/sys/bus/wmi/devices/7A4DDFE7-5B5D-40B4-8595-4408E0CC7F56/' (No such file or directory)

[dsdt.aml.txt](https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module/files/7625380/dsdt.aml.txt)

**Comment by JafarAkhondali** [comment]
Hi,
Looks like your model uses a different approach to handle gaming functions from known models (like mine). Sorry but currently I can't work on it as I don't have enough resources for working on this feature, and it's hard to maintain open source projects.
If you are interested, I gave some details for developing the feature yourself here https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module/issues/21

**Comment by ayan-r** [comment]
Thanks for the answer, I will try to do it
