### ISSUE TITLE
Predator PH315-53 - Install problem

### ISSUE THREAD

**Issue by vladimir-djurovic** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#4]
I follow instructions from README.md and on installation a got this error

My model **Predator PH315-53**

![image](https://user-images.githubusercontent.com/17004266/130780660-6b133dca-f165-429b-8e9f-6b2b5322c01a.png)

**Comment by JafarAkhondali** [comment]
@vladimir-djurovic Hi
Please do the following, and let me know the result:
1. run `sudo apt update && sudo apt install linux-headers-generic` ( if not Debian based, use your own distro package manager)
2. instead of `sh`, use `bash` to run the installer

**Comment by vladimir-djurovic** [comment]
Hi @JafarAkhondali 

Thanks for the reply but I still get the same problem.

I use **Linux Mint 20.2 Cinnamon**, kernel **5.4.0-81-generic** and cinnamon version **5.0.5**

**Comment by vladimir-djurovic** [comment]
Ty @JafarAkhondali,

Turbo Mode is working, but the RGB light still not working.

I tried the following:
![image](https://user-images.githubusercontent.com/17004266/130805168-4262fb82-752c-494d-b02c-4b3ff17e9e7d.png)

,and
![image](https://user-images.githubusercontent.com/17004266/130805237-5d80d386-a837-4f59-8210-922c1cfafc15.png)

**Comment by JafarAkhondali** [comment]
try:
```
sudo ./uninstall.sh
sudo rm /dev/acer-gkbbl-0
sudo ./install.sh
```

and make sure secure boot is disabled in bios.

which of the previous steps did fix the turbo mode problem for you? I wanna add them to code

**Comment by vladimir-djurovic** [comment]
Now works, @JafarAkhondali thank you so much.

To fix the turbo mode, I had to include both header files.

**Comment by alok-37** [comment]
Would have been really helpful if this worked on PH315-55.I did try to install it.It either works occasionally or it doesn't.

**Comment by fjmarcelo** [comment]
> try:
> 
> ```
> sudo ./uninstall.sh
> sudo rm /dev/acer-gkbbl-0
> sudo ./install.sh
> ```
> 
> and make sure secure boot is disabled in bios.
> 
> which of the previous steps did fix the turbo mode problem for you? I wanna add them to code

Same problem, but I can't fix it.

I'm using `Arch Linux` and `Predator PHN16-71`.

What can I do? Thanks in advance.

**Comment by Order52** [comment]
It doesn't work on my Helios 16 PH16-71 it changes nothing when I configure the rgb settings is there a way to this?



Sloppy@bazzite:~/acer-predator-turbo-and-rgb-keyboard-linux-module$ sudo dmidecode | grep "Product Name" -B 2 -A 4
System Information
	Manufacturer: Acer
	Product Name: Predator PH16-71
	Version: V1.16
	Serial Number: NHQJQAA002325186517600
	UUID: ee6a13fd-c099-6445-bf04-74d4dd0896ab
	Wake-up Type: Power Switch
--
Base Board Information
	Manufacturer: RPL
	Product Name: Discovery_RTX
	Version: V1.16
	Serial Number: NBQJQ11001325186517600
	Asset Tag: Type2 - Board Asset Tag
	Features:
Sloppy@bazzite:~/acer-predator-turbo-and-rgb-keyboard-linux-module$ sudo cat /sys/firmware/acpi/tables/DSDT > dsdt.aml
Sloppy@bazzite:~/acer-predator-turbo-and-rgb-keyboard-linux-module$ 

![image](https://github.com/user-attachments/assets/a531ef48-5ecf-4096-9d9a-40b538d7f895)
