### ISSUE TITLE
Not working on Nitro AN515-56

### ISSUE THREAD

**Issue by dhruv8sh** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#43]
RGB model not woking on Acer Nitro AN515-56

**Comment by JafarAkhondali** [comment]
Do you have a 4zone RGB?

**Comment by dhruv8sh** [comment]
@JafarAkhondali Yes, I do have 4-zone RGB.
Worked perfectly fine with NitroSense on Windows.

**Comment by dhruv8sh** [comment]
Started working somehow!!! Thanks alot... Closing this issue but opening a new one.
