### ISSUE TITLE
this modules is working fine in Predator PT315-52

### ISSUE THREAD

**Issue by darkdante14** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#51]
fan and rgb working with this model properly

**Comment by ramonssouza** [comment]
What Linux distribution do you use?  I can't use it on Manjaro and Fedora 36

**Comment by ramonssouza** [comment]
I get kernel panic when shutting down or restarting

**Comment by ramonssouza** [comment]
![IMG_20220708_235532](https://user-images.githubusercontent.com/54721978/178089041-1fa5ca06-d25b-4d6d-852d-947fcac1c0a2.jpg)

**Comment by darkdante14** [comment]
yes its not working on manjaro..but i tried on Garuda and xerolinux and i
also tried on debian like deepin and zorin working perfectly fine

**Comment by ramonssouza** [comment]
opensuse tumbleweed working perfectly fine
