### ISSUE TITLE
Predator PT314-52s doesn't work

### ISSUE THREAD

**Issue by magush27** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#64]
I installed the module in Arch and I can't control RGB colors or turbo fan. I tried the examples but they didn't work.

This is my system info:
`sudo dmidecode | grep "Product Name" -B 2 -A 4`

```
System Information
        Manufacturer: Acer
        Product Name: Predator PT314-52s
        Version: V1.04
        Serial Number: NHQHMAA00121303F687600
        UUID: 51c3bb57-203b-8f46-819a-4b77162d41c9
        Wake-up Type: Power Switch
```

Is there something I can do?

**Comment by JafarAkhondali** [comment]
Hello,
I can't help with the RGB issue, cause I need to own the device to understand the functionality.
For turbo functionality, considering you have 1 fan for GPU and 1 fan for CPU, it may work now.
