### ISSUE TITLE
Acer Nitro 515-58, not working

### ISSUE THREAD

**Issue by deppy-v2** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#68]
# Model: Nitro AN515-58

**Comment by dijia1124** [comment]
Just tested on my AN515-58 running Arch Linux, using "sudo ./install.sh". Keyboard rgb works.

**Comment by deppy-v2** [comment]
I reinstalled on Fedora and it works only until reboot. The service installs fine, but does not work after reboot. Am I missing something here?
![Screenshot_20230529_184025](https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module/assets/116858174/074f2665-e5c7-4e67-8732-c885fdb33068)

**Comment by JafarAkhondali** [comment]
@deppy-v2 Yes, you should install it as a service 
`sudo ./install_service.sh`

**Comment by deppy-v2** [comment]
Thanks, I see it installed and running, but shows no affect on lights. It only has affect until reboot. After that it resets to default behavior and color. Any clues?

**Comment by JafarAkhondali** [comment]
Fixed in last update
