### ISSUE TITLE
Predator PH315-54 works

### ISSUE THREAD

**Issue by TheTrueZeroTwo** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#73]
# Model: `sudo dmidecode | grep "Product Name" -B 2 -A 4`
# Predator PH315-54
### Using fedora 36

**Comment by snowyoneill** [comment]
Confirmed it also works on my PH315-54

**Comment by evaldoavelar** [comment]
Work fine at Pop!_OS 22.04 LTS!

**Comment by jayrfs** [comment]
Thanks for confirming y'all. I'll add this to the readme.
