### ISSUE TITLE
Dual Botting Issue

### ISSUE THREAD

**Issue by TheJarmanitor** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#8]
Hello Jafar. First congratulations and thanks for this repo

I wanted to point out that the installation stops working if you dual boot windows. I had to re install it afterwards.

Not sure if there's  a solution to it but i wanted to let you know.

Thanks again for this amazing code and i hope more people find it

**Comment by JafarAkhondali** [comment]
Hi @TheJarmanitor 
Actually the project is not persistent yet, this has nothing to do with dual-booting. I have dual boot windows as well.
