### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nathancfr** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#82]
Hello,

Is there any documentation available for directly interacting with the device file?

**Comment by JafarAkhondali** [comment]
Hi, what do you mean by device file?
Best you can have is only ` ./facer_rgb.py --help`, otherwise you'll have to reverse engineer stuff yourself

**Comment by nathancfr** [comment]
Hello and thanks for your reply,

With device file I mean the files `/dev/acer-gkbbl-static-0` and `/dev/acer-gkbbl-0`. I'll try to reverse engineer them myself.

**Comment by JafarAkhondali** [comment]
Your welcome. These are character devices that I made that'll communicate with kernel-space.
You can't reverse engineer them. These are just bridges and the doc is enough in `facer_rgb.py`.
