### ISSUE TITLE
PT516-52s RGB working, Turbo not working

### ISSUE THREAD

**Issue by NiklasWilson** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#92]
PT516-52s
This laptop seems to have 3 RGB zones. Static RGB commands are working for zones 1-3.
The turbo button is not working though.

### System Information
	Manufacturer: Acer
	Product Name: Predator PT516-52s
	Version: V1.04
	Wake-up Type: Power Switch

### Base Board Information
	Manufacturer: ADL
	Product Name: Volante_ADH
	Version: V1.04
	Asset Tag: Type2 - Board Asset Tag
	Features:

**Comment by JafarAkhondali** [comment]
Hi, thanks for informing! Does your laptop have a turbo button?

**Comment by quentingllmt** [comment]
Hi @NiklasWilson, 

I have installed ubuntu 22.04 on this computer but I'm facing an issue where the screen (backlight) starts flickering (rapid flashes) after a suspend / sleep on low brightness. The screen does not flashes on first boot or on full brightness.

Do you have the same problem ?

**Comment by NiklasWilson** [comment]
> Hi, thanks for informing! Does your laptop have a turbo button?

Yes it has a turbo button. After awhile I figured out the issue was that Linux didn’t see that my laptop had any fans. I gave up trying to resolve the issue and went back to windows.

**Comment by NiklasWilson** [comment]
> Hi @NiklasWilson,
> 
> I have installed ubuntu 22.04 on this computer but I'm facing an issue where the screen (backlight) starts flickering (rapid flashes) after a suspend / sleep on low brightness. The screen does not flashes on first boot or on full brightness.
> 
> Do you have the same problem ?

**Comment by quentingllmt** [comment]
> > Hi @NiklasWilson,
> > I have installed ubuntu 22.04 on this computer but I'm facing an issue where the screen (backlight) starts flickering (rapid flashes) after a suspend / sleep on low brightness. The screen does not flashes on first boot or on full brightness.
> > Do you have the same problem ?
> 
> i was using Linux mint, and did not have any of these issues.

Is tried linux mint (Cinnamon) and I see the same issue..
