### ISSUE TITLE
Error when installing on predator triton 500, ubuntu 22.04

### ISSUE THREAD

**Issue by ccunarro** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#93]
"kobject_add_internal failed for acer-gkbbl with -EEXIST, don't try to register things with the same name in the same directory."

Here are the full logs when running the command.

![Screenshot-2](https://user-images.githubusercontent.com/9767801/230739580-f5aa24d2-c2a2-4eb2-b5e3-f115cdadf3b1.png)

Any ideas of what could be going on?
What other info would be useful to troubleshoot?

I am using the noveau open source driver for video at the moment.

**Comment by Evan-aja** [comment]
Have you ever installed the module prior to this instance? if yes maybe try to uninstall then install the module. everything works fine for me on kernel 6.2.10.

**Comment by JafarAkhondali** [comment]
Make sure you didn't used install service at first. Uninstall everything, reboot, then reinstall again using the service install script

**Comment by IllusionMan1212** [comment]
This should be fixed by #121
